faculty_template = 'static/faculty/index.html'
student_template = 'static/student/index.html'
unauthenticated_template = 'index.html'
stats_template = 'static/stats/index.html'
list_template = 'list.html'
admin_template = 'static/myadmin/index.html'