version: "2"
services:
  nginx:
    image: nginx
    volumes: [ 
      './nginx.conf:/etc/nginx/nginx.conf',
      '/home/junaid/code/django/achievement_portal/client:/var/www',
      '/usr/share/portal/media:/var/www/media']
    ports: ["80:80"]
    network_mode: "host"
  web:
    build: .
    network_mode: "host"
    volumes: [ '/usr/share/portal/media:/var/www/media' ]
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn achievement_portal.wsgi -b 127.0.0.1:5000'
  