version: "2"
services:
  nginx:
    image: nginx
    volumes: [ 
      './nginx.conf:/etc/nginx/nginx.conf',
      '${HOST_STATIC}:${GUEST_STATIC}',
      '${HOST_MEDIA}:${GUEST_MEDIA}']
    ports: ["80:80"]
    network_mode: "host"
  web:
    build: .
    network_mode: "host"
    volumes: [ '${HOST_MEDIA}:${GUEST_MEDIA}' ]
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn achievement_portal.wsgi -b 127.0.0.1:5000'
  