# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.CharField(max_length=500)),
                ('_title', models.CharField(default='', max_length=1000)),
                ('_year', models.IntegerField(default=0)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Document')),
                ('_verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='_document_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended'),
        ),
    ]
