# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_usn', models.CharField(max_length=40)),
                ('_fname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Document')),
                ('_verified_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='_document_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student'),
        ),
    ]
