# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_file', models.FileField(upload_to='')),
                ('_title', models.CharField(default='', max_length=1000)),
                ('_year', models.IntegerField(default=0)),
                ('_place', models.CharField(default='', max_length=400)),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_verified', models.BooleanField(default=False)),
                ('_year_of_doc', models.IntegerField(default=0)),
                ('_scope', models.CharField(default='', max_length=20)),
                ('_type', models.CharField(default='', max_length=20)),
                ('_avail_for_verification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_at', models.DateTimeField(auto_now_add=True)),
                ('_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Document')),
                ('_verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended'),
        ),
    ]
