# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='_document_of',
            new_name='user',
        ),
    ]
