# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifieddoc',
            name='_verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Faculty'),
        ),
    ]
