# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='_avail_for_verification',
            field=models.BooleanField(default=False),
        ),
    ]
