# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_document__avail_for_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='_verfied',
            new_name='_verified',
        ),
    ]
