# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170806_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='_year_of_doc',
            new_name='_date',
        ),
    ]
