# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170729_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='_user',
        ),
    ]
