# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170729_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='_file',
            field=models.FileField(upload_to=''),
        ),
    ]
