# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170806_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='_date',
            field=models.DateField(default=0),
        ),
    ]
