# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170806_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='_date',
            field=models.DateField(),
        ),
    ]
