# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170726_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extended',
            old_name='is_student',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='document',
            name='_document_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended'),
        ),
        migrations.AlterField(
            model_name='verifieddoc',
            name='_verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Extended'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
